name: Autoupdate project structure
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # at the end of every day

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install cruft poetry jello tabulate

      - name: Update project structure
        run: |
          cruft update -y

      - name: Check if there are changes
        id: changes
        run: echo "changed=$(git status --porcelain | wc -l)" >> "$GITHUB_OUTPUT"

      - name: apply additional changes and fixes
        if: steps.changes.outputs.changed > 0
        run: |
          poetry lock  # add new dependencies
          poetry install
          poetry run pre-commit run -a || true  # we have to fix other issues manually

      - name: Get template versions
        id: get_versions
        if: steps.changes.outputs.changed > 0
        shell: bash
        run: |
          current_version=$(git show HEAD:.cruft.json | jello -r "_['commit'][:8]")
          next_version=$(jello -r "_['commit'][:8]" < .cruft.json)
          echo "current_version=$current_version" >> "$GITHUB_OUTPUT"
          echo "next_version=$next_version" >> "$GITHUB_OUTPUT"

      - name: Get changelog
        if: steps.changes.outputs.changed > 0
        shell: bash
        run: |
          template=$(jello -r "_['template']" < .cruft.json)
          git clone "$template" /tmp/template
          table=$( (echo "Date;Change;Hash"; git -C /tmp/template log --pretty=format:"%as;%s;%h" ${{ steps.get_versions.outputs.current_version }}..${{ steps.get_versions.outputs.next_version }}) | tabulate --header --format github -s ';' -)
          {
            echo "Changes from $template"
            echo ""
            echo "$table"
          } > "$GITHUB_WORKSPACE/template_changelog.md"

      # behaviour if PR already exists: https://github.com/marketplace/actions/create-pull-request#action-behaviour
      - name: Create Pull Request
        env:
          # a PAT is required to be able to update workflows
          GITHUB_TOKEN: ${{ secrets.AUTO_UPDATE_GITHUB_TOKEN }}
        if: ${{ steps.changes.outputs.changed > 0 && env.GITHUB_TOKEN != 0 }}
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ env.GITHUB_TOKEN }}
          commit-message: >-
            chore: update project structure to ${{ steps.get_versions.outputs.next_version }}
          title: "[Actions] Auto-Update cookiecutter template"
          body-path: template_changelog.md
          branch: chore/auto-update-project-from-template
          delete-branch: true
