name: Autoupdate dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/python-poetry-env

      - name: Install tabulate
        run: python -m pip install tabulate

      - name: Gather outdated dependencies
        id: check_for_outdated_dependencies
        shell: bash
        run: echo "count=$(poetry show -o -n | wc -l)" >> "$GITHUB_OUTPUT"

      - name: Format PR message
        if: ${{ steps.check_for_outdated_dependencies.outputs.count > 0 }}
        shell: bash
        run: |
          table=$(poetry show -o -n | sed 's/(!)//' | awk 'BEGIN {print "Package","Used","Update"}; {print $1,$2,$3}' | tabulate --header --format github -)
          {
            echo "The following packages are outdated"
            echo ""
            echo "$table"
          } > "$GITHUB_WORKSPACE/outdated_dependencies.md"

      - name: Update outdated packages
        if: ${{ steps.check_for_outdated_dependencies.outputs.count > 0 }}
        run: poetry lock

      # behaviour if PR already exists: https://github.com/marketplace/actions/create-pull-request#action-behaviour
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.check_for_outdated_dependencies.outputs.count > 0 }}
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ env.GITHUB_TOKEN }}
          commit-message: >-
            chore: update dependencies
          title: "[Actions] Auto-Update dependencies"
          body-path: outdated_dependencies.md
          branch: chore/update-dependencies
          delete-branch: true
